
# Sử dụng hình ảnh cơ sở chứa Apache Tomcat
FROM tomcat:9.0.54-jdk11

# Sao chép file WAR vào thư mục webapps của Tomcat
COPY /target/QuanLyKaraoke.war /usr/local/tomcat/webapps/

# Nếu cần, bạn có thể sao chép các tệp cấu hình hoặc tài nguyên khác vào container
# COPY /path/to/your-config-file /path/to/destination-in-container

# Cung cấp cổng mặc định mà ứng dụng web sẽ chạy
EXPOSE 8080

# Khởi động Tomcat
CMD ["catalina.sh", "run"]
